### PR TITLE
Bulk Reverse Geocoding #4

### LINKED ISSUE #4: Bulk Reverse Geocoding
Add the ability to do a bulk reverse geocoding as a `POST` request through the API:

https://postcodes.io

### PR DESCRIPTION
**Pull request by ddziaduch**
## Description

Implemented feature from #4 

## Motivation and context

To improve the library and have more PRs in the Hacktoberfest :)

fixes #4 

## How has this been tested?

Yes, I tested the API first to make sure what responses are and implement that here.

## Screenshots (if appropriate)

N/A

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by JustSteveKing** [comment]
@ddziaduch there is a conflict on this - once resolved I will merge

**Comment by kayrunm** [comment]
Has this PR been abandoned? Happy to take over if so

**Comment by JustSteveKing** [comment]
@kayrunm yes please!

**Comment by ddziaduch** [comment]
@kayrunm @JustSteveKing sorry I wan't available 😔. I can resolve the conflicts today

**Comment by kayrunm** [comment]
@ddziaduch not to worry, just thought I could help out if you were too busy or something!

**Pull request merged**
