### PR TITLE
Bulk lookup postcodes #2

### PR DESCRIPTION
**Pull request by mikhailkozlov**
## Description

Adding Bulk lookup postcodes and helper function to make POST requests with json payload and optional query string. 

Bulk function will return collection

## Motivation and context

Bulk lookup postcodes #2 and possibly Update Postcode Service #1

## How has this been tested?

I've added test to mock API response and assert results

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by JustSteveKing** [comment]
This is currently failing test, and code could be cleaned up.

**Comment by mikhailkozlov** [comment]
@JustSteveKing Let me know what you would like to be cleaned up.

**Comment by JustSteveKing** [comment]
Currently we have a method for getting a response from the API, what is needed here is optional parameters to turn this into a POST request.

```php
<?php
/**
     * Get the response and return the result object
     *
     * @param string $uri
     */
    protected function getResponse(string $uri = null, string $method = 'GET', array $data = [])
    {
        $url = $this->url . $uri;

        $request = $this->http->request(
            $method,
            $url,
            $data
        );

        return json_decode($request->getBody()->getContents())->result;
    }
?>
```

As a quick example. Also this now has a few conflicting changes

**Comment by mikhailkozlov** [comment]
Got it. I was not sure if "get" in "getResponse" referred to how information will be requested. I'll refactor and make another update PR.

**Comment by mikhailkozlov** [comment]
Conflicts are resolved. I did refactor but added entire options array so it can be used to pass headers and what ever else may be need in future.

**Comment by JustSteveKing** [comment]
Good changes! The only problem I can tell is unused code: https://scrutinizer-ci.com/g/JustSteveKing/LaravelPostcodes/inspections/0a018981-ab6b-4dfe-a131-0dc2e2949c0c/issues/files/src/Service/PostcodeService.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

A minor problem, but no real issue!

**Comment by mikhailkozlov** [comment]
Done

**Pull request merged**
