### PR TITLE
Get nearest outward codes for a given longitude & latitude #11

### PR DESCRIPTION
**Pull request by ddziaduch**
## Description

Added new featured as requested in #11 

## Motivation and context

To help the project and contribute to Hacktoberfest.

## How has this been tested?

1. Checked what are the possible responses from the API.
2. Added new method in the Service.
3. Tested the method via PhpUnit - both cases, success and failure.

## Screenshots (if appropriate)

None

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by JustSteveKing** [comment]
While tests are passing this won't work as an integration

**Comment by ddziaduch** [comment]
@JustSteveKing oh man you are right. Do you want me to return the object or some other kind of structure?

**Comment by JustSteveKing** [comment]
A plain object is fine thank you! I'd like to eventually return something more structured for the addresses but I think that's a future improvement.

**Comment by ddziaduch** [comment]
@JustSteveKing double checked that and I am pretty sure that this returns an array of objects 🙂 The problem here is that I have implemented the wrong method... 🤦🏻‍♂️ The issue was about `Get nearest outward codes for a given longitude & latitude` but I implemented `Get nearest postcodes for a given longitude & latitude`

**Pull request merged**
